development:
  GMAIL_USERNAME: valter.rv2101@gmail.com
  GMAIL_PASSWORD: WalterRizo0911:D
production:
  ADMIN_NAME: admibiosoft
  ADMIN_EMAIL: admin@biosoft.com
  ADMIN_PASSWORD: 12345678
  GMAIL_USERNAME: valter.rv2101@gmail.com
  GMAIL_PASSWORD: WalterRizo0911:D
  DOMAIN_NAME: biosoft.com
  SECRET_KEY_BASE: 3c4328ad6d9ec854ccfb0fe936afd1c22cfc6d96155789e4722c89d84a7077fce5b7b8bfb9b3e4b23355e1bf9f6d2d44632e3fa0bb25cc7fb9159fa34ffb84d5
